civil_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('leave/',include('leave_portal.urls')),

]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

from django.conf.urls.static import static
from . import settings

urlpatterns += static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

leave_portal/urls.py
from django.urls import path,include
from . import views

app_name = "leave_portal"
urlpatterns = [
    path('',views.index , name="HelloWorld"),

    path('dashboard', views.dashboard , name='dashboard'),
    path('dppc/updatedppcdata/<int:pk>',views.DppcUpdateDetail, name="dppc_detail_update"),
    path('hod/updatehoddata/<int:pk>',views.HodUpdateDetail, name="hod_detail_update"),
    path('staff/updatestaffdata/<int:pk>',views.StaffUpdateDetail, name="staff_detail_update"),
    path('staff/updateoddsemester/',views.Update_Odd_Semester, name="update_odd_semester"),
    path('staff/verifyupdateoddsemester/',views.Verify_Update_Odd_Semester, name="verify_update_odd_semester"),
    path('staff/updateevensemester/',views.Update_Even_Semester, name="update_even_semester"),
    path('staff/verifyupdateevensemester/',views.Verify_Update_Even_Semester, name="verify_update_even_semester"),
    path('faculty/updatefacultydata/<int:pk>',views.FacultyUpdateDetail, name="faculty_detail_update"),
    path('<int:pk>' , views.ApplyLeaveDetailView.as_view() , name="leave_info"),
    path('student',views.StudentListView.as_view() , name="studentsList" ),
    path('students/updatedata/<int:pk>',views.StudentUpdateDetail, name="stud_detail_update"),
    path('student/<int:pk>',views.StudentDetailView.as_view(), name="studentsDetail" ),
    path('student/leaveform/<int:pk>', views.ApplyLeave, name="apply_leave"),
    path('student/leaveform/<int:pk>/<int:leave_id>', views.ApplyLeaveEdit, name="apply_leave_edit"),
    path('student/<int:pk>/pending', views.PendingRequest,name="pending_request"),
    path('student/<int:pk>/history', views.History,name="history"),
    path('authorized/pending_request',views.authorized_pending,name="authorized_pending_request"),
    path('authorized/pending_request/approve/<int:pk>',views.approveleave,name="Approve"),
    path('authorized/pending_request/decline/<int:pk>',views.declineleave,name="Decline"),
    path('dppc',views.DppcListView.as_view(), name="dppclist"),
    path('dppc/<int:pk>',views.DppcDetailView.as_view(), name="dppcdetail"),

    path('leaves/info/<int:pk>' , views.LeaveInfo , name="LeavePortal"),
    path('leaves/authorized/info/' , views.AuthorizedLeaveInfo , name="AuthorizedLeavePortal"),
    path('student/taSlipForm/<int:pk>', views.ApplyTaSlip, name="apply_ta_slip"),
    path('slips/info/<int:pk>' , views.SlipsPortal , name="TASlipPortal"),



]

leave_portal/forms.py
from . import models
from django import forms


class LeaveForm(forms.ModelForm):
    class Meta:
        model = models.ApplyLeave
        fields = ['LeaveFrom','LeaveTo','ReasonForLeave','AddressWhileOnLeave','PhoneNumberWhileOnLeave','DateOfApply','TypeOfLeave','Doc1','Doc2','SentTo']

class TASlipForm(forms.ModelForm):
    class Meta:
        model = models.TASlip
        fields = ['startingMonth','endingMonth' ]


class UpdateStudDetail(forms.ModelForm):
    class Meta:
        model = models.Student
        fields = [
            'profile_pic',
            'name',
            'roll_no',
            'gender',
            'webmail',
            'course',
            'hostel_name',
            'room_number',
            'mob_number',
            'emergency_mob_num',
            'TA_instructor',
            'Supervisor_1',
        ]


class UpdateDppcDetail(forms.ModelForm):
    class Meta:
        model = models.Dppc
        fields = [
            'profile_pic',
            'name',
            'webmail',
            'mob_num',
            'dppc_id',
        ]

class UpdateHodDetail(forms.ModelForm):
    class Meta:
        model = models.Hod
        fields = [
            'profile_pic',
            'name',
            'webmail',
            'mob_num',
            'hod_id',
        ]

class UpdateStaffDetail(forms.ModelForm):
    class Meta:
        model = models.Staff
        fields = [
            'profile_pic',
            'name',
            'webmail',
            'mob_num',
            'staff_id',
        ]

class UpdateFacultyDetail(forms.ModelForm):
    class Meta:
        model = models.Faculty
        fields = [
            'profile_pic',
            'name',
            'webmail',
            'mob_num',
            'faculty_id',
        ]

class CommentsForm(forms.ModelForm):
    class Meta:
        model = models.Comments
        fields = [
            'Remark',
        ]

leave_portal/views.py
from django.urls import reverse
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from . import models
from . import forms
from users.models import CustomUser
from .forms import TASlipForm,UpdateStudDetail ,LeaveForm, UpdateHodDetail,UpdateDppcDetail,UpdateHodDetail,UpdateStaffDetail,UpdateFacultyDetail
from django.contrib.auth.decorators import login_required
from datetime import date

@login_required

# dashboard for the users of the software ie . student , dppc , HOD  , faculty

def dashboard(request):

    # if the user is student
    if request.user.person=='student':
        student = models.Student.objects.filter(user=request.user)

        # if the student has registered for the first time,
        # he will be asked to fill the form
        if not student :
            if request.method=='POST' :

                form = UpdateStudDetail(request.POST , request.FILES )
                if form.is_valid():
                    detail = form.save(commit=False)
                    detail.user = request.user
                    detail.save()
                return redirect('leave_portal:dashboard')
            else :
                form = UpdateStudDetail(request.POST)
                return render(request,'leave_portal/StudDetail.html', {'form':form , 'student':request.user.username} )

        # else he will be directed towards his dashboard
        else:
            student = models.Student.objects.get(user=request.user)
            forms = models.ApplyLeave.objects.filter(student=student).order_by('-DateOfApply')
            return render(request,'leave_portal/dashboard.html',{'user':request.user , 'student':student, 'forms':forms})

    # if the user is a DPPC
    elif request.user.person=='dppc':
        dppc = models.Dppc.objects.filter(user=request.user)

        # as in student, if dppc is logging in for the first time
        if not dppc :
            form =  UpdateDppcDetail()
            if request.method=='POST' :
                form =  UpdateDppcDetail(request.POST)
                if form.is_valid():
                    detail = form.save(commit=False)
                    detail.user = request.user
                    detail.save()
                    #we are getting an error
                return redirect('leave_portal:dashboard')
            else :
                return render(request,'leave_portal/dppc_update_detail.html', {'form':form , 'dppc':request.user.username} )

        # else he will be directed to hos dashbpard
        else:
            authorized = models.Dppc.objects.get(user=request.user)
            forms=models.ApplyLeave.objects.filter(flag=3,ApprovedStatus='pending')
            return render(request,'leave_portal/authorized_dashboard.html',{'user':request.user , 'authorized':authorized, 'forms':forms})

    # if the user logging in is the HOD
    elif request.user.person=='hod':
        hod = models.Hod.objects.filter(user=request.user)

        #  if the HOD is logging in for the first time
        if not hod :
            form =  UpdateHodDetail()
            if request.method=='POST' :
                form =  UpdateHodDetail(request.POST)
                if form.is_valid():
                    detail = form.save(commit=False)
                    detail.user = request.user
                    detail.save()
                    #we are getting an error
                return redirect('leave_portal:dashboard')
            else :
                return render(request,'leave_portal/dppc_update_detail.html', {'form':form , 'dppc':request.user.username} )

        # else HOD is taken to his dashboard
        else:
            authorized = models.Hod.objects.get(user=request.user)
            forms=models.ApplyLeave.objects.filter(flag=5,ApprovedStatus__iexact='pending')
            return render(request,'leave_portal/authorized_dashboard.html',{'user':request.user , 'authorized':authorized, 'forms':forms})

    #  similar coding has been done for the staff and the faculty users

    elif request.user.person=='staff':
        staff = models.Staff.objects.filter(user=request.user)
        if not staff :
            form =  UpdateStaffDetail()
            if request.method=='POST' :
                form =  UpdateStaffDetail(request.POST)
                if form.is_valid():
                    detail = form.save(commit=False)
                    detail.user = request.user
                    detail.save()
                    #we are getting an error
                return redirect('leave_portal:dashboard')
            else :
                return render(request,'leave_portal/dppc_update_detail.html', {'form':form , 'dppc':request.user.username} )
        else:
            authorized = models.Staff.objects.get(user=request.user)
            forms=models.ApplyLeave.objects.filter(flag=4,ApprovedStatus__iexact='pending')
            return render(request,'leave_portal/authorized_dashboard.html',{'user':request.user , 'authorized':authorized , 'forms':forms})

    elif request.user.person=='faculty':
        faculty = models.Faculty.objects.filter(user=request.user)
        if not faculty :
            form =  UpdateFacultyDetail()
            if request.method=='POST' :
                form =  UpdateFacultyDetail(request.POST)
                if form.is_valid():
                    detail = form.save(commit=False)
                    detail.user = request.user
                    detail.save()
                    #we are getting an error
                return redirect('leave_portal:dashboard')
            else :
                return render(request,'leave_portal/dppc_update_detail.html', {'form':form , 'dppc':request.user.username} )
        else:
            authorized = models.Faculty.objects.get(user=request.user)
            forms1=models.ApplyLeave.objects.filter(student__TA_instructor__user=request.user ,flag=1,ApprovedStatus__iexact='pending')
            forms2=models.ApplyLeave.objects.filter(student__Supervisor_1__user=request.user ,flag=2,ApprovedStatus__iexact='pending')
            forms=forms1 | forms2
            return render(request,'leave_portal/authorized_dashboard.html',{'user':request.user , 'authorized':authorized , 'forms':forms})

#  function was used for testing purposes
def index(request):
    return HttpResponse("HelloWorld!!")

# generic view to display all rhe students we have registered in our database
class StudentListView(generic.ListView):
    model = models.CustomUser
    context_object_name = 'student_list'
    queryset = CustomUser.objects.filter(person__iexact='student') # Get 5 books containing the title war
    template_name = 'leave_portal/student_list.html'

# generic view to display all the information of a student basec on hos id
class StudentDetailView(generic.DetailView):
    model = models.Student

class ApplyLeaveDetailView(generic.DetailView):
    model = models.ApplyLeave

#  function that will be called when student requests for a leave
def ApplyLeave(request,pk):
    student = get_object_or_404(models.Student, pk=pk)
    form =  LeaveForm()

    if request.method == 'POST':
        form =  LeaveForm(request.POST)
        if form.is_valid():
            leave = form.save(commit=False)
            leave.student = student

            if '1' in leave.SentTo:
                leave.flag=1

            if '2' in leave.SentTo and leave.flag is 0:
                leave.flag=2

            if '3' in leave.SentTo:
                leave.flag=3

            leave.save()
            return HttpResponseRedirect(student.get_absolute_url())
    return render(request, 'leave_portal/leaveform.html', {'student':student, 'form':form})

#change flag accordingly

# function to make changes to the leave
def ApplyLeaveEdit(request, pk, leave_id):
    student = get_object_or_404(models.Student, pk=pk)
    leave = get_object_or_404(models.ApplyLeave, pk=leave_id, student=student)

    form =  LeaveForm(instance=leave)

    if request.method == 'POST':
        form =  LeaveForm(instance=leave, data=request.POST)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(student.get_absolute_url())

    return render(request, 'leave_portal/leaveform.html', {'form':form, 'student':student})

class DppcListView(generic.ListView):
    model = models.Dppc

class DppcDetailView(generic.DetailView):
    model = models.Dppc

# function that allows the student to uodate his profile
def StudentUpdateDetail(request, pk):
    student = get_object_or_404(models.Student, pk=pk)
    form =  UpdateStudDetail( instance = student)

    if request.method == 'POST' :
        form =  UpdateStudDetail( request.POST  , request.FILES , instance = student )
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(student.get_absolute_url())

    return render(request, 'leave_portal/StudDetail.html', {'form':form, 'student':student})

# just like the case for the student we have functions that will update the profiles
# of the HOD , DPPC , staff and the faculty

def DppcUpdateDetail(request, pk):
    dppc = get_object_or_404(models.Dppc, pk=pk)
    form =  UpdateDppcDetail(instance=dppc)

    if request.method == 'POST':
        form =  UpdateDppcDetail( request.POST  , request.FILES , instance = dppc)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(dppc.get_absolute_url())

    return render(request, 'leave_portal/dppc_update_detail.html', {'form':form, 'authorized':dppc})

def HodUpdateDetail(request, pk):
    hod = get_object_or_404(models.Hod, pk=pk)
    form =  UpdateHodDetail(instance=hod)

    if request.method == 'POST':
        form =  UpdateHodDetail( request.POST  , request.FILES , instance = hod )
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(hod.get_absolute_url())

leave_portal/templates/leave_portal/authorizedLeaveInfo.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'leave_portal/css/stud_dashboard.css' %}">
{% endblock %}
{% block content %}
<div class="wrapper">
    <nav id="sidebar">
        <ul class="list-unstyled components">
          <p><img class="profile" src="/media/{{authorized.profile_pic}}" ></p>
          {% if authorized %}
            {% if authorized.dppc_id %}
              <a href="{% url 'leave_portal:dppc_detail_update' authorized.id %}"><p class="options">Edit Detail</p></a>
            {% elif authorized.hod_id %}
              <a href="{% url 'leave_portal:hod_detail_update' authorized.id %}"><p class="options">Edit Detail</p></a>
            {% elif authorized.staff_id %}
              <a href="{% url 'leave_portal:staff_detail_update' authorized.id %}"><p class="options">Edit Detail</p></a>
            {% elif authorized.faculty_id %}

              <a href="{% url 'leave_portal:faculty_detail_update' authorized.id %}"><p class="options">Edit Detail</p></a>
            {% endif %}
          {% endif %}
          <a href="{% url 'leave_portal:AuthorizedLeavePortal' %}"><p class="options">See all leaves</p></a>
          
        </ul>
    </nav>
    <div id="page-content-wrapper">
        <h1>Pending Request</h1>
        {% if forms %}
        {% for form in forms %}
          <div class="Requests">
            <div class = "row">
              <div class = "information col-lg-10 col-md-10 col-sm-12">
                 <span style="font-weight:bold;">Name : </span> {{form.student}} <br />
                  <span style="font-weight:bold;">Reason For Leave :</span> {{form.ReasonForLeave}} <br />
                  <span style="font-weight:bold;">Requested Tenure :</span> {{form.LeaveFrom}} - {{form.LeaveTo}} <br />
                  <span style="font-weight:bold;">Date Of Apply :</span> {{form.DateOfApply}} <br />
              </div>
              <div class = "col-lg-2 col-md-2 col-sm-12">
                <button class="requestbutton btn btn-info" onclick="window.location='{% url 'leave_portal:leave_info' form.id %}'" type="button" class="btn btn-sm ">View Form</button>
                <button class="requestbutton btn btn-success" onclick="window.location='{% url 'leave_portal:Approve' form.id %}'" type="button" class="btn btn-sm ">Approve</button>
                <button class="requestbutton btn btn-danger" onclick="window.location='{% url 'leave_portal:Decline' form.id %}'" type="button" class="btn btn-sm ">Decline</button>
              </div>
            </div>
          </div>
          <hr width="125%" class="my-4">
        {% endfor %}
        {% else %}
        <p class="jumbotron">No Leave Requests Right Now !!</p>
        {% endif %}
    </div>
</div>
{% endblock%}

leave_portal/templates/leave_portal/authorized_dashboard.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'leave_portal/css/stud_dashboard.css' %}">
{% endblock %}
{% block content %}
<div class="wrapper">
    <nav id="sidebar">
        <ul class="list-unstyled components">
          <p><img class="profile" src="/media/{{authorized.profile_pic}}" ></p>
          {% if authorized %}
            {% if authorized.dppc_id %}
              <a href="{% url 'leave_portal:dppc_detail_update' authorized.id %}"><p class="options">Edit Detail</p></a>
            {% elif authorized.hod_id %}
              <a href="{% url 'leave_portal:hod_detail_update' authorized.id %}"><p class="options">Edit Detail</p></a>
            {% elif authorized.staff_id %}
              <a href="{% url 'leave_portal:staff_detail_update' authorized.id %}"><p class="options">Edit Detail</p></a>
              <a href="{% url 'leave_portal:verify_update_odd_semester' %}"><p class="options">Update Odd Semester</p></a>
              <a href="{% url 'leave_portal:verify_update_even_semester' %}"><p class="options">Update Even Semester</p></a>
            {% elif authorized.faculty_id %}

              <a href="{% url 'leave_portal:faculty_detail_update' authorized.id %}"><p class="options">Edit Detail</p></a>
            {% endif %}
          {% endif %}

          <a href="{% url 'leave_portal:AuthorizedLeavePortal' %}"><p class="options">See all leaves</p></a>

        </ul>
    </nav>
    <div id="page-content-wrapper">

    </div>
</div>
{% endblock%}

leave_portal/templates/leave_portal/confirm_even_sem.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'leave_portal/css/stud_dashboard.css' %}">
{% endblock %}
{% block content %}
<div class="wrapper">
    <nav id="sidebar">
        <ul class="list-unstyled components">
          <p><img class="profile" src="/media/{{authorized.profile_pic}}" ></p>
          {% if authorized %}
            {% if authorized.dppc_id %}
              <a href="{% url 'leave_portal:dppc_detail_update' authorized.id %}"><p class="options">Edit Detail</p></a>
            {% elif authorized.hod_id %}
              <a href="{% url 'leave_portal:hod_detail_update' authorized.id %}"><p class="options">Edit Detail</p></a>
            {% elif authorized.staff_id %}
              <a href="{% url 'leave_portal:staff_detail_update' authorized.id %}"><p class="options">Edit Detail</p></a>
              <a href="{% url 'leave_portal:verify_update_odd_semester' %}"><p class="options">Update Odd Semester</p></a>
              <a href="{% url 'leave_portal:verify_update_even_semester' %}"><p class="options">Update Even Semester</p></a>
            {% elif authorized.faculty_id %}

              <a href="{% url 'leave_portal:faculty_detail_update' authorized.id %}"><p class="options">Edit Detail</p></a>
            {% endif %}
          {% endif %}

          <a href="{% url 'leave_portal:AuthorizedLeavePortal' %}"><p class="options">See all leaves</p></a>

        </ul>
    </nav>
    <div id="page-content-wrapper">
        <div class="jumbotron">
            <p>Are You Sure You Want To End The Even Semester ?</p>
            <a class="btn btn-lg btn-success" href="{% url 'leave_portal:update_even_semester' %}">YES</a>
            <a class="btn btn-lg btn-success" href="{% url 'leave_portal:dashboard' %}">NO</a>
        </div>
    </div>
</div>
{% endblock%}

leave_portal/templates/leave_portal/dppc_list.html
{% extends "base_generic.html" %}

{% block title%}All Dppc{% endblock%}

{% block content %}

{% if dppc_list %}
<ul>
  {% for dppc in dppc_list %}
      <li><a href="{% url 'leave_portal:dppcdetail' pk=dppc.id %}">{{dppc.name}}</a>({{dppc.dppc_id}})</li>
    {% empty %}
  {% endfor %}
</ul>

{% else %}
<p class="jumbotron">Sorry but no dppc!!</p>
{% endif %}

{% endblock %}

leave_portal/templates/leave_portal/studentLeaveInfo.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'leave_portal/css/stud_dashboard.css' %}">
{% endblock %}
{% block content %}
<div class="wrapper">
  <nav id="sidebar">
      <ul class="list-unstyled components">
        <p><img class="profile" src="/media/{{student.profile_pic}}" ></p>
        <a href="{% url 'leave_portal:stud_detail_update' student.id %}"><p class="options">Edit Detail</p></a>
        <a href="{% url 'leave_portal:apply_leave' student.id %}"><p class="options">Apply Leave</p></a>
        <a href="{% url 'leave_portal:LeavePortal' student.id %}"><p class="options">See all leaves</p></a>
        <a href="{% url 'leave_portal:apply_ta_slip' student.id %}"><p class="options">Apply for TA SLIP</p></a>
        <a href="{% url 'leave_portal:TASlipPortal' student.id %}"><p class="options">See all TA Slips</p></a>
      </ul>
  </nav>
    <div id="page-content-wrapper">
        <h1>Pending Request</h1>
        {% if forms %}
        <ol>
          {% for form in forms %}
            {% if form.ApprovedStatus == 'pending' %}

              <li><h3>Reasons of leave : {{form.ReasonForLeave}}</h3></li>
              <ul>
                <a href="{% url 'leave_portal:leave_info' pk=form.id %}" style = "float : right;"><input type="button" class="btn btn-info"  value="View Form" /></a>

              <li>Requested tenure : {{form.LeaveFrom}} - {{form.LeaveTo}} </li>
              <li>Date of Apply : {{form.DateOfApply}}</li>
              </li>
              <li>Status :<span class ="text-warning"> Pending</span></li>
              <li>In-Process :<span class= "text-primary">
              {% if form.flag == 1 %}
                TA/Instructor {{ student.TA_instructor }}
              {% elif form.flag == 2 %}
                Supervisor {{ student.Supervisor_1 }}
              {% elif form.flag == 3 %}
                Dppc
              {% elif form.flag == 4 %}
                Staff
              {% elif form.flag == 5 %}
                Hod
              {% endif %}
            </span>
            </li>
            </ul>

            {% endif %}
          {% endfor %}
        </ol>
        {% else %}
          <p class="text-info"> Sorry but you have no forms pending!!! </p>
        {% endif %}

        <h1>History</h1>
            {% if forms %}
            <ol>
              {% for form in forms %}
              <div class="container-fluid">

                {% if form.ApprovedStatus == "approved" %}
                  <li><h3>Reasons of leave : {{form.ReasonForLeave}}</h3></li>
                  </li>
                  <ul>
                  <a href="{% url 'leave_portal:leave_info' pk=form.id %}" style = "float : right;"><input type="button" class="btn btn-info" value="View Form" /></a>

                  <li>Requested tenure : {{form.LeaveFrom}} - {{form.LeaveTo}} </li>
                  <li>Date of Apply : {{form.DateOfApply}}</li>
                  Status : <span class = "text-success"> Approved </span>
                  </ul>
                {% endif %}

                {% if form.ApprovedStatus == "declined" %}
                  <li>
                  <h3>Reasons of leave : {{form.ReasonForLeave}}</h3></li>
                  </li>
                  <ul>
                  <a href="{% url 'leave_portal:leave_info' pk=form.id %}" style = "float : right;"><input type="button" class="btn btn-info" value="View Form" /></a>
                  <li>Requested tenure : {{form.LeaveFrom}} - {{form.LeaveTo}} </li>
                  <li>Date of Apply : {{form.DateOfApply}}</li>

                  Status : <span class="text-danger">Declined</span>
                  </ul>
                {% endif %}

              </div>

              {% endfor %}
            </ol>
            {% else %}
              <p>Sorry but you have not filled any forms yet!!! </p>
            {% endif %}
    </div>
</div>
{% endblock%}

leave_portal/templates/leave_portal/xyz.html
{% extends "base_generic.html" %}
{% load static %}
{% block css %}
  <link rel="stylesheet" href="{% static 'leave_portal/css/stud_dashboard.css' %}">
{% endblock %}
{% block content %}
<div class="wrapper">
    <nav id="sidebar">
        <ul class="list-unstyled components">
          <p><img class="profile" src="/media/{{student.profile_pic}}" ></p>
          {% if authorized %}
            {% if authorized.dppc_id %}
              <button onclick="window.location='{% url 'leave_portal:dppc_detail_update' authorized.id %}'" type="button" class="btn btn-md ">Edit Detail</button>
            {% elif authorized.hod_id %}
              <button onclick="window.location='{% url 'leave_portal:hod_detail_update' authorized.id %}'" type="button" class="btn btn-md ">Edit Detail</button>
            {% elif authorized.staff_id %}
              <button onclick="window.location='{% url 'leave_portal:staff_detail_update' authorized.id %}'" type="button" class="btn btn-md ">Edit Detail</button>
            {% elif authorized.faculty_id %}
              <button onclick="window.location='{% url 'leave_portal:faculty_detail_update' authorized.id %}'" type="button" class="btn btn-md ">Edit Detail</button>
            {% endif %}
          {% endif %}
        </ul>
    </nav>
    <div id="page-content-wrapper">
        <h1>Pending Request</h1>
        % if forms %}
        {% for form in forms %}
          <p> {{form.student}} {{form.ReasonForLeave}} </p>
          <button onclick="window.location='{% url 'leave_portal:leave_info' form.id %}'" type="button" class="btn btn-sm ">View Form</button>
          <button onclick="window.location='{% url 'leave_portal:Approve' form.id %}'" type="button" class="btn btn-sm ">Approve</button>
          <button onclick="window.location='{% url 'leave_portal:Decline' form.id %}'" type="button" class="btn btn-sm ">Decline</button>
        {% endfor %}
        {% else %}
        <p class="jumbotron">No Leave Requests Right Now !!</p>
        {% endif %}
    </div>
</div>
{% endblock%}







{% extends "base_generic.html" %}

{% block title%}{{authorized.name}}{% endblock %}

{% block content %}

  {% if authorized %}
  <h1 class="jumbotron">{{authorized.name}}</h1>
    {% if authorized.dppc_id %}
      <button onclick="window.location='{% url 'leave_portal:dppc_detail_update' authorized.id %}'" type="button" class="btn btn-md ">Edit Detail</button>
    {% elif authorized.hod_id %}
      <button onclick="window.location='{% url 'leave_portal:hod_detail_update' authorized.id %}'" type="button" class="btn btn-md ">Edit Detail</button>
    {% elif authorized.staff_id %}
      <button onclick="window.location='{% url 'leave_portal:staff_detail_update' authorized.id %}'" type="button" class="btn btn-md ">Edit Detail</button>
    {% elif authorized.faculty_id %}
      <button onclick="window.location='{% url 'leave_portal:faculty_detail_update' authorized.id %}'" type="button" class="btn btn-md ">Edit Detail</button>
    {% endif %}
  <button onclick="window.location='{% url 'leave_portal:authorized_pending_request' %}'" type="button" class="btn btn-md ">Pending Requests</button>
  <button onclick="window.location='{% url 'account_logout' %}'" type="button" class="btn btn-md ">Log Out!!</button>
  {% endif %}

{% endblock %}